# Generated by Codex on 2026-07-07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountChangeLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("change_type", models.CharField(choices=[("email", "이메일"), ("password", "비밀번호"), ("security", "보안")], max_length=20, verbose_name="변경유형")),
                ("field_name", models.CharField(max_length=50, verbose_name="항목")),
                ("old_value", models.CharField(blank=True, max_length=255, verbose_name="이전값")),
                ("new_value", models.CharField(blank=True, max_length=255, verbose_name="변경값")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="변경일시")),
                ("changed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="account_changes_made", to=settings.AUTH_USER_MODEL, verbose_name="변경자")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="account_change_logs", to=settings.AUTH_USER_MODEL, verbose_name="회원")),
            ],
            options={
                "verbose_name": "계정 수정 이력",
                "verbose_name_plural": "계정 수정 이력",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="accountchangelog",
            index=models.Index(fields=["user", "-created_at"], name="accounts_ac_user_id_6b4bd4_idx"),
        ),
    ]