# Generated by Codex on 2026-07-07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_accountchangelog"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="accountchangelog",
            new_name="accounts_ac_user_id_f57c3e_idx",
            old_name="accounts_ac_user_id_6b4bd4_idx",
        ),
    ]