# Generated by Django 5.0.6 on 2026-07-03 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='미션명')),
                ('target_count', models.PositiveIntegerField(default=1, verbose_name='목표횟수')),
                ('reward_point', models.PositiveIntegerField(default=0, verbose_name='보상포인트')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
            ],
            options={
                'verbose_name': '미션',
                'verbose_name_plural': '미션',
                'indexes': [models.Index(fields=['is_active'], name='gamificatio_is_acti_51175d_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', '미시작'), ('in_progress', '진행중'), ('completed', '완료')], default='not_started', max_length=20, verbose_name='상태')),
                ('progress_count', models.PositiveIntegerField(default=0, verbose_name='진행횟수')),
                ('is_completed', models.BooleanField(default=False, verbose_name='완료')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료일')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_missions', to='gamification.mission', verbose_name='미션')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_missions', to=settings.AUTH_USER_MODEL, verbose_name='회원')),
            ],
            options={
                'verbose_name': '회원 미션',
                'verbose_name_plural': '회원 미션',
            },
        ),
        migrations.CreateModel(
            name='PointLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('submission_created', '문제풀이완료'), ('solve_success', '정답처리'), ('wrongnote_completed', '오답노트작성'), ('review_completed', '복습완료'), ('daily_mission_completed', '미션완료'), ('admin_adjustment', '관리자조정')], max_length=30, verbose_name='행동유형')),
                ('point', models.IntegerField(verbose_name='포인트')),
                ('related_model', models.CharField(blank=True, max_length=50, verbose_name='관련모델')),
                ('related_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='관련ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='지급일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_logs', to=settings.AUTH_USER_MODEL, verbose_name='회원')),
            ],
            options={
                'verbose_name': '포인트 로그',
                'verbose_name_plural': '포인트 로그',
                'indexes': [models.Index(fields=['user', 'action_type'], name='gamificatio_user_id_ad050e_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='pointlog',
            constraint=models.UniqueConstraint(fields=('user', 'action_type', 'related_model', 'related_id'), name='uniq_point_award'),
        ),
        migrations.AddConstraint(
            model_name='usermission',
            constraint=models.UniqueConstraint(fields=('user', 'mission'), name='uniq_user_mission'),
        ),
    ]
