# Generated by Django 5.0.6 on 2026-07-03 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0001_initial'),
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WrongNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, verbose_name='사용자코멘트')),
                ('ai_analysis', models.JSONField(blank=True, default=dict, verbose_name='AI분석')),
                ('error_pattern', models.CharField(blank=True, max_length=100, verbose_name='오류패턴')),
                ('status', models.CharField(choices=[('draft', '작성중'), ('completed', '완료'), ('indexed', '인덱싱완료'), ('index_failed', '인덱싱실패')], default='draft', max_length=20, verbose_name='상태')),
                ('is_reviewed', models.BooleanField(default=False, verbose_name='복습완료')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='복습일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wrong_notes', to='problems.problem', verbose_name='문제')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wrong_notes', to='submissions.submission', verbose_name='제출')),
                ('tags', models.ManyToManyField(blank=True, related_name='wrong_notes', to='problems.problemtag', verbose_name='태그')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wrong_notes', to=settings.AUTH_USER_MODEL, verbose_name='회원')),
            ],
            options={
                'verbose_name': '오답노트',
                'verbose_name_plural': '오답노트',
            },
        ),
        migrations.CreateModel(
            name='WrongNoteQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(verbose_name='질의')),
                ('answer', models.TextField(blank=True, verbose_name='답변')),
                ('evidence_note_ids', models.JSONField(blank=True, default=list, verbose_name='근거노트ID')),
                ('scores', models.JSONField(blank=True, default=list, verbose_name='점수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_query_logs', to=settings.AUTH_USER_MODEL, verbose_name='회원')),
            ],
            options={
                'verbose_name': '내 노트 질의 로그',
                'verbose_name_plural': '내 노트 질의 로그',
            },
        ),
        migrations.CreateModel(
            name='WrongNoteVector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding_id', models.CharField(max_length=128, verbose_name='임베딩ID')),
                ('source', models.CharField(default='wrong_note', max_length=30, verbose_name='출처')),
                ('indexed_at', models.DateTimeField(blank=True, null=True, verbose_name='인덱싱시각')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wrong_note_vectors', to=settings.AUTH_USER_MODEL, verbose_name='회원')),
                ('wrong_note', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vector', to='wrongnotes.wrongnote', verbose_name='오답노트')),
            ],
            options={
                'verbose_name': '오답노트 벡터',
                'verbose_name_plural': '오답노트 벡터',
            },
        ),
        migrations.AddIndex(
            model_name='wrongnote',
            index=models.Index(fields=['user', 'status', 'created_at'], name='wrongnotes__user_id_5bd433_idx'),
        ),
        migrations.AddIndex(
            model_name='wrongnotequerylog',
            index=models.Index(fields=['user', 'created_at'], name='wrongnotes__user_id_ab952c_idx'),
        ),
        migrations.AddIndex(
            model_name='wrongnotevector',
            index=models.Index(fields=['user'], name='wrongnotes__user_id_8c8525_idx'),
        ),
    ]
