# Generated by Django 5.0.6 on 2026-07-03 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(verbose_name='제출코드')),
                ('result', models.CharField(choices=[('pending', '대기'), ('success', '정답'), ('wrong', '오답'), ('error', '오류'), ('timeout', '시간초과')], default='pending', max_length=20, verbose_name='채점결과')),
                ('output', models.TextField(blank=True, verbose_name='실행출력')),
                ('error_message', models.TextField(blank=True, verbose_name='오류메시지')),
                ('elapsed_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='실행시간(ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='제출일')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='problems.problem', verbose_name='문제')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='회원')),
            ],
            options={
                'verbose_name': '제출',
                'verbose_name_plural': '제출',
            },
        ),
        migrations.CreateModel(
            name='ExecutionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('code_run', '코드실행')], default='code_run', max_length=20, verbose_name='작업유형')),
                ('status', models.CharField(choices=[('pending', '대기'), ('running', '실행중'), ('success', '성공'), ('failed', '실패'), ('timeout', '시간초과')], default='pending', max_length=20, verbose_name='처리상태')),
                ('input_payload', models.JSONField(blank=True, default=dict, verbose_name='입력페이로드')),
                ('result_payload', models.JSONField(blank=True, default=dict, verbose_name='결과페이로드')),
                ('retry_count', models.PositiveIntegerField(default=0, verbose_name='재시도횟수')),
                ('max_retry', models.PositiveIntegerField(default=1, verbose_name='최대재시도')),
                ('worker_id', models.CharField(blank=True, max_length=64, verbose_name='워커ID')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='시작시각')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='종료시각')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL, verbose_name='회원')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='submissions.submission', verbose_name='제출')),
            ],
            options={
                'verbose_name': '실행작업',
                'verbose_name_plural': '실행작업',
            },
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['user', 'problem', 'created_at'], name='submissions_user_id_7ddccf_idx'),
        ),
        migrations.AddIndex(
            model_name='executionjob',
            index=models.Index(fields=['status', 'created_at'], name='submissions_status_99b42f_idx'),
        ),
    ]
