# Generated by Django 5.0.6 on 2026-07-06 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_submission_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='submission',
            new_name='submissions_user_id_8e75cf_idx',
            old_name='submissions_user_id_ee78f2_idx',
        ),
        migrations.AlterField(
            model_name='executionjob',
            name='job_type',
            field=models.CharField(choices=[('code_run', '코드실행'), ('code_submit', '코드제출'), ('code_eval', '코드평가')], default='code_run', max_length=20, verbose_name='작업유형'),
        ),
        migrations.AlterField(
            model_name='executionjob',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='submissions.submission', verbose_name='제출'),
        ),
        migrations.AlterField(
            model_name='executionjob',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL, verbose_name='회원'),
        ),
    ]
