# Generated by Django 5.0.6 on 2026-07-09 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_rename_submissions_user_id_ee78f2_idx_submissions_user_id_8e75cf_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executionjob',
            name='job_type',
            field=models.CharField(choices=[('code_run', '코드실행'), ('code_submit', '코드제출'), ('code_eval', '코드평가'), ('testcase_gen', '테스트케이스생성')], default='code_run', max_length=20, verbose_name='작업유형'),
        ),
    ]
