# Generated by Django 5.0.6 on 2026-07-07 02:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, verbose_name='AI 요약')),
                ('level', models.CharField(blank=True, max_length=30, verbose_name='추정 수준')),
                ('strengths', models.JSONField(blank=True, default=list, verbose_name='강점')),
                ('weaknesses', models.JSONField(blank=True, default=list, verbose_name='약점')),
                ('recurring_mistakes', models.JSONField(blank=True, default=list, verbose_name='반복 실수')),
                ('recommended_focus', models.JSONField(blank=True, default=list, verbose_name='학습 방향')),
                ('stats_snapshot', models.JSONField(blank=True, default=dict, verbose_name='집계 스냅샷')),
                ('source_submission_count', models.PositiveIntegerField(default=0, verbose_name='기준 제출 수')),
                ('model', models.CharField(blank=True, max_length=64, verbose_name='모델')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='갱신')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coding_state', to=settings.AUTH_USER_MODEL, verbose_name='회원')),
            ],
            options={
                'verbose_name': '코딩 상태(AI 내부값)',
                'verbose_name_plural': '코딩 상태(AI 내부값)',
            },
        ),
    ]
