# Generated by Django 5.0.6 on 2026-07-09 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codingstate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingstate',
            name='refresh_count',
            field=models.PositiveIntegerField(default=0, verbose_name='갱신 횟수'),
        ),
        migrations.AddField(
            model_name='codingstate',
            name='thinking_profile',
            field=models.TextField(blank=True, verbose_name='사고 추적 메모리'),
        ),
    ]
