# Generated by Django 5.0.6 on 2026-07-03 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('django', 'Django'), ('fastapi', 'FastAPI'), ('worker', 'Worker'), ('chromadb', 'ChromaDB'), ('openai', 'OpenAI'), ('deploy', '배포')], max_length=20, verbose_name='발생원')),
                ('level', models.CharField(default='error', max_length=20, verbose_name='레벨')),
                ('path', models.CharField(blank=True, max_length=255, verbose_name='경로')),
                ('error_type', models.CharField(blank=True, max_length=100, verbose_name='오류유형')),
                ('message', models.TextField(blank=True, verbose_name='메시지')),
                ('traceback', models.TextField(blank=True, verbose_name='트레이스백')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='해결됨')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='발생일')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_logs', to=settings.AUTH_USER_MODEL, verbose_name='회원')),
            ],
            options={
                'verbose_name': '에러 로그',
                'verbose_name_plural': '에러 로그',
                'indexes': [models.Index(fields=['source', 'level', 'created_at'], name='logs_errorl_source_a9b659_idx')],
            },
        ),
        migrations.CreateModel(
            name='LLMRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('hint', '힌트'), ('wrong_note_search', '오답검색'), ('wrong_note_analyze', '오답분석'), ('wrong_note_embed', '오답임베딩'), ('note_ask', '내노트질의')], max_length=30, verbose_name='요청유형')),
                ('request_id', models.CharField(max_length=64, unique=True, verbose_name='요청ID')),
                ('input_text', models.TextField(blank=True, verbose_name='입력')),
                ('response_text', models.TextField(blank=True, verbose_name='응답')),
                ('status', models.CharField(choices=[('pending', '대기'), ('processing', '처리중'), ('success', '성공'), ('failed', '실패'), ('timeout', '시간초과'), ('empty', '결과없음')], default='pending', max_length=20, verbose_name='상태')),
                ('error_type', models.CharField(blank=True, max_length=100, verbose_name='오류유형')),
                ('error_message', models.TextField(blank=True, verbose_name='오류메시지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료시각')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_logs', to=settings.AUTH_USER_MODEL, verbose_name='회원')),
            ],
            options={
                'verbose_name': 'LLM 요청 로그',
                'verbose_name_plural': 'LLM 요청 로그',
                'indexes': [models.Index(fields=['status'], name='logs_llmreq_status_0a76bc_idx')],
            },
        ),
    ]
