# Generated by Django 5.0.6 on 2026-07-03 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('slug', models.SlugField(unique=True, verbose_name='슬러그')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='정렬순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
            ],
            options={
                'verbose_name': '문제 카테고리',
                'verbose_name_plural': '문제 카테고리',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProblemTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('slug', models.SlugField(unique=True, verbose_name='슬러그')),
            ],
            options={
                'verbose_name': '문제 태그',
                'verbose_name_plural': '문제 태그',
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('description', models.TextField(verbose_name='설명')),
                ('difficulty', models.CharField(choices=[('basic', '언어기초'), ('beginner', '초급'), ('intermediate', '중급'), ('advanced', '고급')], default='beginner', max_length=20, verbose_name='난이도')),
                ('constraints', models.TextField(blank=True, verbose_name='제약조건')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='problems', to='problems.problemcategory', verbose_name='카테고리')),
                ('tags', models.ManyToManyField(blank=True, related_name='problems', to='problems.problemtag', verbose_name='태그')),
            ],
            options={
                'verbose_name': '문제',
                'verbose_name_plural': '문제',
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField(blank=True, verbose_name='입력')),
                ('expected_output', models.TextField(blank=True, verbose_name='기대출력')),
                ('is_sample', models.BooleanField(default=False, verbose_name='샘플공개')),
                ('compare_mode', models.CharField(choices=[('exact', '완전일치'), ('line_trim', '줄단위공백정리'), ('float', '부동소수점오차허용')], default='line_trim', max_length=20, verbose_name='채점방식')),
                ('float_tolerance', models.FloatField(default=1e-06, verbose_name='부동소수허용오차')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='problems.problem', verbose_name='문제')),
            ],
            options={
                'verbose_name': '테스트케이스',
                'verbose_name_plural': '테스트케이스',
            },
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['category', 'difficulty'], name='problems_pr_categor_af19d5_idx'),
        ),
        migrations.AddIndex(
            model_name='testcase',
            index=models.Index(fields=['problem'], name='problems_te_problem_71dd6a_idx'),
        ),
    ]
